FROM ros:jazzy

# ── rosbridge_suite ───────────────────────────────────────────────────────────
RUN apt-get update && apt-get install -y \
    ros-jazzy-rosbridge-server \
    ros-jazzy-rosbridge-library \
    ros-jazzy-rosapi \
    ros-jazzy-vision-msgs \
    ros-jazzy-rosidl-pycommon

# ── Entrypoint ────────────────────────────────────────────────────────────────
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# WebSocket port
ENV ROSBRIDGE_PORT=9099
EXPOSE 9099

ENTRYPOINT ["/entrypoint.sh"]


